import MainContainer from '@/components/MainContainer'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Webmon - next.js 13',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <MainContainer>
        {children}
      </MainContainer>

    </html>
  )
}
